name: odin_cloth_wear
description: "Odin Cloth Wear Website"

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.1.0
  riverpod: ^2.4.9
  flutter_animate: ^4.4.1
  equatable: ^2.0.5
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  cached_network_image: ^3.3.1
  http: ^1.2.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  crypto: ^3.0.3
  firebase_storage: ^11.6.0
  eva_icons_flutter: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/font/Rubik.ttf
    - assets/logo/logo.png

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik.ttf
flutter_launcher_icons:
  #flutter pub run flutter_launcher_icons:main
  image_path: "assets/logo/logo.png"
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#F7F7F7"
    theme_color: "#F7F7F7"
flutter_native_splash:
  # dart run flutter_native_splash:create
  color: "#F7F7F7"
  image: assets/logo/logo.png
  web: true
  web_image_mode: center
  fullscreen: true
