name: odin_cloth_wear
description: "Odin Cloth Wear Website"

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.14.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0
  expandable: ^5.0.1
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.5
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.9
  flutter_svg: ^1.0.3
  fluttertoast: ^8.2.4
  go_router: ^13.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  riverpod: ^2.4.9
  responsive_framework: ^1.1.1
  shimmer: ^3.0.0
  url_strategy: ^0.2.0

dev_dependencies:
  animated_native_splash:
    git:
      url: https://github.com/OmarHosamCodes/flutter_animated_splash_screen
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
    - assets/images/wrapBackground.png
    - assets/images/wrapBackgroundBright.png
    - assets/animation/splashAnimation.json

flutter_launcher_icons:
  #flutter pub run flutter_launcher_icons:main
  image_path: "assets/logo/logo.png"
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#F7F7F7"
    theme_color: "#F7F7F7"

flutter_native_splash:
  # dart run flutter_native_splash:create
  color: "#F7F7F7"
  image: assets/logo/logo.png
  web: true
  web_image_mode: center
  fullscreen: true

animated_native_splash:
  jsonFile: assets/animation/splashAnimation.json
